### ISSUE TITLE
grpc worker not closed on finish

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tikv-client-java#101]
maybe the close() is not functioning in the right way

**Comment by zhexuany** [comment]
Could you please give a guide about how to reproduce?

**Comment by ilovesoup** [comment]
Just the main.java can reproduce it. If you finish the main thread, grpc thread still working. Seems we forget to call some of the closing function.

**Comment by zhexuany** [comment]
The following is what we are missing. 
```
cluster.close();
client.close();
```

put above statement at end of main.java should resolve this problem.

**Comment by birdstorm** [comment]
As a matter of fact,  we have already enclosed those statements while the issue still exists.

**Comment by zhexuany** [comment]
@birdstorm It works on my machine.

**Comment by zhexuany** [comment]
Closing, fixed on #107

**Comment by birdstorm** [comment]
Previously fixed by #107 , however we are now facing the same issue because of multithreading. There isn't any thread hook for us to call `close()` when main thread has ended, resulting in failure to end other worker threads.

**Comment by zhexuany** [comment]
More details? Even class implements `AutoClose`, it is till need in a try-resources block in order to actually auto close and release resources.

**Comment by ilovesoup** [comment]
The problem here is, connections and threads are shared across tasks. We can't just simply close it. Easier way might be set threads to daemon. If you want a explicit close,  you need a hook on executor close on TiSpark part.

**Comment by birdstorm** [comment]
Seems difficult to reproduce the same issue. Chances are that when you run spark-shell you cannot quit spark normally without interruption. By calling `jps` you can see spark-shell hangs on with grpc still running. I can't tell whether it is fixed or not in the newest master branch.

**Comment by ilovesoup** [comment]
I believe this has been fixed. https://github.com/pingcap/tikv-client-lib-java/pull/139
