### ISSUE TITLE
Cannot read data normally if schema is changed

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tikv-client-java#161]
When table schema is changed in MySQL client or TiDB, we experience errror in reading and retrieving data correctly.
```
scala> spark.sql("select * from a").show(truncate=false);
+-----------+--------------------+
|id_int     |id_bigint           |
+-----------+--------------------+
|-2147483648|-9223372036854775808|
+-----------+--------------------+
```

Now we do some DDL operations:
```
mysql> alter table a add column ts timestamp;
Query OK, 0 rows affected (0.27 sec)

mysql> select * from a;
+-------------+----------------------+---------------------+
| id_int      | id_bigint            | ts                  |
+-------------+----------------------+---------------------+
| -2147483648 | -9223372036854775808 | 2017-11-28 14:10:02 |
+-------------+----------------------+---------------------+
1 row in set (0.00 sec)
```

After schema changed:
```
scala> spark.sql("select * from a").show(truncate=false);
+-----------+--------------------+
|id_int     |id_bigint           |
+-----------+--------------------+
|-2147483648|-9223372036854775808|
+-----------+--------------------+
```

**Comment by birdstorm** [comment]
Update:

If we restart spark-shell and re-select the result from altered tables, we will encounter Errors (easily reproduced).

```
scala> spark.sql("select * from a").show(truncate=false)
17/11/28 14:13:35 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
com.pingcap.tikv.exception.TiClientInternalException: Error reading region
	at com.pingcap.tikv.operation.SelectIterator.readNextRegion(SelectIterator.java:163)
	at com.pingcap.tikv.operation.SelectIterator.hasNext(SelectIterator.java:176)
	at org.apache.spark.sql.tispark.TiRDD$$anon$2.hasNext(TiRDD.scala:75)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:231)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:225)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:826)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:826)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: com.pingcap.tikv.exception.SelectException: unknown error StringError("column 3 of 1 is missing")
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.pingcap.tikv.operation.SelectIterator.readNextRegion(SelectIterator.java:160)
	... 17 more
Caused by: com.pingcap.tikv.exception.SelectException: unknown error StringError("column 3 of 1 is missing")
	at com.pingcap.tikv.region.RegionStoreClient.coprocessorHelper(RegionStoreClient.java:192)
	at com.pingcap.tikv.region.RegionStoreClient.coprocess(RegionStoreClient.java:185)
	at com.pingcap.tikv.operation.SelectIterator.createClientAndSendReq(SelectIterator.java:134)
	at com.pingcap.tikv.operation.SelectIterator.lambda$submitTasks$2(SelectIterator.java:116)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
17/11/28 14:13:35 ERROR TaskSetManager: Task 0 in stage 0.0 failed 1 times; aborting job
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): com.pingcap.tikv.exception.TiClientInternalException: Error reading region
	at com.pingcap.tikv.operation.SelectIterator.readNextRegion(SelectIterator.java:163)
	at com.pingcap.tikv.operation.SelectIterator.hasNext(SelectIterator.java:176)
	at org.apache.spark.sql.tispark.TiRDD$$anon$2.hasNext(TiRDD.scala:75)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:231)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:225)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:826)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:826)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: com.pingcap.tikv.exception.SelectException: unknown error StringError("column 3 of 1 is missing")
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.pingcap.tikv.operation.SelectIterator.readNextRegion(SelectIterator.java:160)
	... 17 more
Caused by: com.pingcap.tikv.exception.SelectException: unknown error StringError("column 3 of 1 is missing")
	at com.pingcap.tikv.region.RegionStoreClient.coprocessorHelper(RegionStoreClient.java:192)
	at com.pingcap.tikv.region.RegionStoreClient.coprocess(RegionStoreClient.java:185)
	at com.pingcap.tikv.operation.SelectIterator.createClientAndSendReq(SelectIterator.java:134)
	at com.pingcap.tikv.operation.SelectIterator.lambda$submitTasks$2(SelectIterator.java:116)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

Driver stacktrace:
  at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:1918)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:1931)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:1944)
  at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:333)
  at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:38)
  at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$execute$1$1.apply(Dataset.scala:2371)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
  at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2765)
  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$execute$1(Dataset.scala:2370)
  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collect(Dataset.scala:2377)
  at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2113)
  at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2112)
  at org.apache.spark.sql.Dataset.withTypedCallback(Dataset.scala:2795)
  at org.apache.spark.sql.Dataset.head(Dataset.scala:2112)
  at org.apache.spark.sql.Dataset.take(Dataset.scala:2327)
  at org.apache.spark.sql.Dataset.showString(Dataset.scala:248)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:638)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:615)
  ... 48 elided
Caused by: com.pingcap.tikv.exception.TiClientInternalException: Error reading region
  at com.pingcap.tikv.operation.SelectIterator.readNextRegion(SelectIterator.java:163)
  at com.pingcap.tikv.operation.SelectIterator.hasNext(SelectIterator.java:176)
  at org.apache.spark.sql.tispark.TiRDD$$anon$2.hasNext(TiRDD.scala:75)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:231)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:225)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:826)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:826)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
  at org.apache.spark.scheduler.Task.run(Task.scala:99)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: com.pingcap.tikv.exception.SelectException: unknown error StringError("column 3 of 1 is missing")
  at java.util.concurrent.FutureTask.report(FutureTask.java:122)
  at java.util.concurrent.FutureTask.get(FutureTask.java:192)
  at com.pingcap.tikv.operation.SelectIterator.readNextRegion(SelectIterator.java:160)
  ... 17 more
Caused by: com.pingcap.tikv.exception.SelectException: unknown error StringError("column 3 of 1 is missing")
  at com.pingcap.tikv.region.RegionStoreClient.coprocessorHelper(RegionStoreClient.java:192)
  at com.pingcap.tikv.region.RegionStoreClient.coprocess(RegionStoreClient.java:185)
  at com.pingcap.tikv.operation.SelectIterator.createClientAndSendReq(SelectIterator.java:134)
  at com.pingcap.tikv.operation.SelectIterator.lambda$submitTasks$2(SelectIterator.java:116)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  ... 3 more
```

**Comment by birdstorm** [comment]
There might be issues involving schema not updated each time as it should.

**Comment by birdstorm** [comment]
Cause found and now fixing by @zhexuany . 

Will be moved to TiSpark side. Closing.

**Comment by zhexuany** [comment]
thought is problem from spark side. But it is actually not.  Following main function can confirm it is a problem in java client side. 
```
  public static void main(String[] args) throws Exception {
    TiConfiguration conf = TiConfiguration.createDefault("127.0.0.1:2379");
    TiSession session = TiSession.create(conf);
    Catalog cat = session.getCatalog();
    TiDBInfo db = cat.getDatabase("test");
    TiTableInfo table = cat.getTable(db, "t2");
    Snapshot snapshot = session.createSnapshot();
    TiSelectRequest selectRequest = new TiSelectRequest();
    ScanBuilder scanBuilder = new ScanBuilder();
    ScanBuilder.ScanPlan scanPlan = scanBuilder.buildScan(new ArrayList<>(), table);
    selectRequest.addRequiredColumn(TiColumnRef.create("c1", table))
        .addRequiredColumn(TiColumnRef.create("ts", table))
        .setStartTs(snapshot.getVersion())
        .addRanges(scanPlan.getKeyRanges())
        .setTableInfo(table);
    Iterator<Row> it = snapshot.tableRead(selectRequest);
    while (it.hasNext()) {
      Row r = it.next();
      SchemaInfer schemaInfer = SchemaInfer.create(selectRequest);
      for (int i = 0; i < r.fieldCount(); i++) {
        Object val = r.get(i, schemaInfer.getType(i));
        System.out.print(val);
      }
    }
    session.close();
  }
```

**Comment by Novemser** [comment]
May need to integrate with cache invalidation framework to let driver know when to update schema information.

**Comment by zhexuany** [comment]
@Novemser It is not a problem in Spark side. W/o Spark, compile this project with above `Main` class, you can reproduce this problem. It should be a problem in our reading table logic.

**Comment by ilovesoup** [comment]
@birdstorm Did we confirm this has been fixed before close issue？

**Comment by birdstorm** [comment]
@ilovesoup I just tested on master branch. The behavior now is quite weird:

Firstly the table schema is still not refreshed after alter operation were executed in mysql side, no matter whether you remap or redefine `ti`, this remains the same as original issue description.

The behavior after restarting spark-shell is strange, we are not throwing errors after restarting. 

More specifically, if we use `alter table a add column ts int;`, we can output the correct table content with a default `NULL` column concatenated to its end. (Well that's normal)

But if we use `alter table a add column ts timestamp;` to alter target table, instead we are outputting an empty table.

When we use `alter table a add column ts int default 0;`, the concatenated column remains `NULL`. 

There might be multiple issues concerning these outputs. Can anyone reproduce this? @zhexuany @Novemser

**Comment by ilovesoup** [comment]
@birdstorm Anything can be resolve by restart, is likely due to meta cache out of date. For now it's controlled by spark.tispark.meta.reload_period_in_sec which by default is 60s.
If restart cannot resolve the issue, we need some deep investigation.

**Comment by Novemser** [comment]
@zhexuany Would you please specify which version of `tikv-client-lib-java` you are using?

**Comment by zhexuany** [comment]
@Novemser You can create two identical table and alter one of them. Say these table names are t1 and t2. And you choose alter table t1, you can try to run `Main` function. Of course, you also need adjust parameter in the `Main`. You can probably reproduce this bug.

**Comment by zhexuany** [comment]
Root cause is we did not set default value when we build our select request. I am working on it right now.
